# Generated by Django 3.0.6 on 2020-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('it', models.BooleanField()),
                ('cs', models.BooleanField()),
            ],
        ),
    ]
